### ISSUE TITLE
Dataset related question.

### ISSUE THREAD

**Issue by LloydZhang** [abhyudaynj/LSTM-CRF-models#4]
Thank your for sharing the coeds! I've read your paper and wonder could you please provide the dataset used on this work?

Best Regards!

**Comment by sandeepsingh** [comment]
@LloydZhang  did you get the labeled dataset for this?

**Comment by abhyudaynj** [comment]
Hello,  The dataset used in this was compiled and released as a part of a joint NER and Relation extraction Dataset [MADE 1.0](https://www.ncbi.nlm.nih.gov/pubmed/30649735). 

Please submit a request for the dataset [here](https://bio-nlp.org/index.php/announcements/41-change-in-data-recipient-agreement-for-made1-0)
